config/routes.rb
Pelisbox::Application.routes.draw do
  resources :estrenos

  devise_for :uploaders

  resources :peliculas

  root :to => 'peliculas#principal'

end

app/models/estreno.rb
class Estreno < ActiveRecord::Base
  attr_accessible :categoria, :descripcion, :iframe, :imagen, :nota, :opcion1, :opcion2, :titulo
end

app/models/pelicula.rb
class Pelicula < ActiveRecord::Base
	extend FriendlyId
	belongs_to :uploader
  attr_accessible :descripcion, :iframe, :imagen, :titulo, :uploader_id, :trailer
  friendly_id :titulo

#Metodo para exportar a CSV
  def self.to_csv 
  	CSV.generate do |csv|
  		csv << column_names
  		all.each do |product|
  			csv << product.attributes.values_at(*column_names)
  		end
  	end
  end

def self.text_search(query)
  if query.present?
    where("titulo @@ :q", q: "%#{query}%")
  else
    scoped
  end
end
  
end

app/models/uploader.rb
class Uploader < ActiveRecord::Base
	has_many :peliculas
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :footers 
 def footers
   Pelicula.find(:all, :order => 'created_at DESC', :limit => 5)
 end

end

app/controllers/estrenos_controller.rb
class EstrenosController < ApplicationController
  # GET /estrenos
  # GET /estrenos.json
  def index
    @estrenos = Estreno.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estrenos }
    end
  end

  # GET /estrenos/1
  # GET /estrenos/1.json
  def show
    @estreno = Estreno.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estreno }
    end
  end

  # GET /estrenos/new
  # GET /estrenos/new.json
  def new
    @estreno = Estreno.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estreno }
    end
  end

  # GET /estrenos/1/edit
  def edit
    @estreno = Estreno.find(params[:id])
  end

  # POST /estrenos
  # POST /estrenos.json
  def create
    @estreno = Estreno.new(params[:estreno])

    respond_to do |format|
      if @estreno.save
        format.html { redirect_to @estreno, notice: 'Estreno was successfully created.' }
        format.json { render json: @estreno, status: :created, location: @estreno }
      else
        format.html { render action: "new" }
        format.json { render json: @estreno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estrenos/1
  # PUT /estrenos/1.json
  def update
    @estreno = Estreno.find(params[:id])

    respond_to do |format|
      if @estreno.update_attributes(params[:estreno])
        format.html { redirect_to @estreno, notice: 'Estreno was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estreno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estrenos/1
  # DELETE /estrenos/1.json
  def destroy
    @estreno = Estreno.find(params[:id])
    @estreno.destroy

    respond_to do |format|
      format.html { redirect_to estrenos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
  before_filter :authenticate_uploader!, except: [:principal, :show]
  # GET /peliculas
  # GET /peliculas.json
  def index
    @peliculas = Pelicula.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @peliculas }
      format.csv { send_data @pelicula.to_csv }
    end
  end

  def principal
    @peliculas = Pelicula.page(params[:page]).per(12)
    @estrenos = Estreno.all(:order => "created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @peliculas }
    end
  end

  def principal2
    @peliculas = Pelicula.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @peliculas }
    end
  end

  # GET /peliculas/1
  # GET /peliculas/1.json
  def show
    @pelicula = Pelicula.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pelicula }
    end
  end

  # GET /peliculas/new
  # GET /peliculas/new.json
  def new
    @pelicula = Pelicula.new
    @cuantas = Pelicula.where(uploader_id: 'current_uploader.id').count()


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pelicula }
    end
  end

  # GET /peliculas/1/edit
  def edit
    @pelicula = Pelicula.find(params[:id])
  end

  # POST /peliculas
  # POST /peliculas.json
  def create
    @pelicula = Pelicula.new(params[:pelicula])
    @pelicula.uploader_id = current_uploader.id 


    respond_to do |format|
      if @pelicula.save
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully created.' }
        format.json { render json: @pelicula, status: :created, location: @pelicula }
      else
        format.html { render action: "new" }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /peliculas/1
  # PUT /peliculas/1.json
  def update
    @pelicula = Pelicula.find(params[:id])

    respond_to do |format|
      if @pelicula.update_attributes(params[:pelicula])
        format.html { redirect_to @pelicula, notice: 'Pelicula was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pelicula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /peliculas/1
  # DELETE /peliculas/1.json
  def destroy
    @pelicula = Pelicula.find(params[:id])
    @pelicula.destroy

    respond_to do |format|
      format.html { redirect_to peliculas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estrenos_helper.rb
module EstrenosHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/views/estrenos/_form.html.erb
<%= form_for(@estreno) do |f| %>
  <% if @estreno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@estreno.errors.count, "error") %> prohibited this estreno from being saved:</h2>

      <ul>
      <% @estreno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br />
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :nota %><br />
    <%= f.text_field :nota %>
  </div>
  <div class="field">
    <%= f.label :categoria %><br />
    <%= f.text_field :categoria %>
  </div>
  <div class="field">
    <%= f.label :iframe %><br />
    <%= f.text_area :iframe %>
  </div>
  <div class="field">
    <%= f.label :opcion1 %><br />
    <%= f.text_area :opcion1 %>
  </div>
  <div class="field">
    <%= f.label :opcion2 %><br />
    <%= f.text_area :opcion2 %>
  </div>
  <div class="field">
    <%= f.label :imagen %><br />
    <%= f.text_field :imagen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/estrenos/edit.html.erb
<h1>Editing estreno</h1>

<%= render 'form' %>

<%= link_to 'Show', @estreno %> |
<%= link_to 'Back', estrenos_path %>

app/views/estrenos/index.html.erb
<h1>Listing estrenos</h1>

<table>
  <tr>
    <th>Titulo</th>
    <th>Descripcion</th>
    <th>Nota</th>
    <th>Categoria</th>
    <th>Iframe</th>
    <th>Opcion1</th>
    <th>Opcion2</th>
    <th>Imagen</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @estrenos.each do |estreno| %>
  <tr>
    <td><%= estreno.titulo %></td>
    <td><%= estreno.descripcion %></td>
    <td><%= estreno.nota %></td>
    <td><%= estreno.categoria %></td>
    <td><%= estreno.iframe %></td>
    <td><%= estreno.opcion1 %></td>
    <td><%= estreno.opcion2 %></td>
    <td><%= estreno.imagen %></td>
    <td><%= link_to 'Show', estreno %></td>
    <td><%= link_to 'Edit', edit_estreno_path(estreno) %></td>
    <td><%= link_to 'Destroy', estreno, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Estreno', new_estreno_path %>

app/views/estrenos/new.html.erb
<h1>Agregar Estreno</h1>

<%= render 'form' %>

<%= link_to 'Back', estrenos_path %>

app/views/estrenos/show.html.erb
<%- model_class = Estreno -%>


<div class="row">
  <div class="span8" id="estreno_iframe">
    <div class="iframe"><%= raw @estreno.iframe %></div>
  </div>
  <div class="span4" style="text-align:center;">
    <h1 style="color:white;"><%= @estreno.titulo %></h1>
     <p style="color:white;"><%= @estreno.descripcion %></p>
  </div>
</div>
<div class="row">
  <div class="span4">
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PelisBoxNet | Peliculas en español, subtituladas. Estrenos Buena calidad VK</title>
  <meta name="description" content="PelisBox Ver peliculas online subtitulada gratis estrenos" />
  <meta name="keywords" content="Ver peliculas online subtituladas gratis estrenos buena calidad español" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Condiment' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Anaheim' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="fb-root">
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=200273886775051";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script></div>
	<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35868775-1']);
  _gaq.push(['_setDomainName', 'pelisbox.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<div class="container">
  	<div class="row">
      

      <div class="span4">
        <div class="logo">
          <a href="http://www.pelisbox.net"><img src="http://imagenes.todoonline.tv/pelisboxlogo.png" /></a>
        </div>
      </div>
      
      <div class="span8" id="barra">
        

      </div>
    
    </div>


<%= yield %>
</div>


<div class="container" id="footer">
  <div class="row" id="foot">

    <div class="span3" id="footer_uno">
      <h4><%= link_to 'PELISBOX 2012', root_path %></h4>
    </div>

    <div class="span3" id="footer_dos">
      <h3> Últimas peliculas </h3>
      <ul>
        <% footers.each do |f| %>
        <li><%= link_to "#{f.titulo}", pelicula_path(f) %></li>
        <% end %>
      </ul>
    </div>

    <div class="span3" id="footer_dos">
      <h3> Contacto </h3>
      <ul>
      <li> Siguenos en Twitter <a href="https://twitter.com/PelisBoxnet">@PelisBoxNet</a> </li>
      </ul>

  </div>

</div>

</body>
</html>

app/views/peliculas/_carousel.html.erb
<div id="myCarousel" class="carousel slide">
                <div class="carousel-inner">
                  <div class="item active">
                    <img src="<%= @estrenos.first.imagen %>">
                    <div class="carousel-caption">
                      <h4><%= link_to "#{@estrenos.first.titulo}", estreno_path(@estrenos.first) %></h4>
                    </div>
                  </div>
                  <div class="item">
                    <img src="<%= @estrenos.second.imagen %>">
                    <div class="carousel-caption">
                      <h4><%= link_to "#{@estrenos.second.titulo}", estreno_path(@estrenos.second) %></h4>
                    </div>
                  </div>


                  
                </div>
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>

app/views/peliculas/_form.html.erb
<%= form_for @pelicula, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :titulo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :titulo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descripcion, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :iframe, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :iframe, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :imagen, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :imagen, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :trailer, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :trailer, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                peliculas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/peliculas/edit.html.erb
<%- model_class = Pelicula -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/peliculas/index.html.erb
<div class="row"> 
  <div class="span4 offset4">
    <% if uploader_signed_in? %>
      Logged in as <strong><%= current_uploader.email %></strong>.
      <%= link_to "Logout", destroy_uploader_session_path, method: :delete %>
    <% else %>
      <%= link_to "R", new_uploader_registration_path %> |
      <%= link_to "Entrar", new_uploader_session_path %>
    <% end %>
  </div>
</div>

<%- model_class = Pelicula -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:titulo) %></th>
      <th><%= model_class.human_attribute_name(:imagen) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @peliculas.each do |pelicula| %>
      <tr>
        <td><%= link_to "#{pelicula.titulo}", pelicula_path(pelicula) %></td>
        <td><%= raw pelicula.imagen %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_pelicula_path(pelicula), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      pelicula_path(pelicula),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_pelicula_path,
            :class => 'btn btn-primary' %>

<%= link_to 'Volver', root_path %>

app/views/peliculas/new.html.erb
<%- model_class = Pelicula -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>
<div class="uploader">
	<h2>Subido por: <%= current_uploader.email %> </h2>
</div>

app/views/peliculas/principal.html.erb
<%- model_class = Pelicula -%>

<div class="row" id="principal">
	<div class="span8">
		<h3 id="ultimas"> Últimas Agregadas </h3>
    <% @peliculas.order("created_at DESC").each do |pelicula| %>
      <div class="view view-first">
          <%= raw pelicula.imagen %>
          <div class="mask">
	          <h2><%= link_to "#{pelicula.titulo}", pelicula_path(pelicula) %></h2>	
	        </div>
      </div>
      <% end %>
    <div class="row">
    	<div class="span8">
    		<%= paginate @peliculas %>
    	</div>
    </div> 
  </div>


  <div class="span4" id="estrenos">
  	<div class="row" id="estreno">
  		<%= render :partial => 'carousel' %>
  	</div>
  </div>
</div>

app/views/peliculas/principal2.html.erb
<div class="row">
	<div class="span4 offset1">
		<div class="logo">
			<img src="http://imagenes.todoonline.tv/pelisboxlogo.png" />
		</div>
	</div>
</div>

app/views/peliculas/show.html.erb
<%- model_class = Pelicula -%>


<div class="row" id="show">
	<div class="span8" id="estreno_iframe">
		<div class="iframe" style="text-align:center;"><%= raw @pelicula.iframe %></div>
	</div>
	<div class="span4" id="desc"style="text-align:center;">
		<h1><%= @pelicula.titulo %></h1>
		 <p style="color:black;"><%= @pelicula.descripcion %></p>
		</br>
		<h1 style="color: #19A206;">Trailer </h1>
		<iframe width="360" height="200" src="http://www.youtube.com/embed/<%= raw @pelicula.trailer %>" frameborder="0" allowfullscreen></iframe>
	</div>
</div>
<div class="row">
	<div class="span8">
		<div class="fb-comments" data-href="http://pelisbox.net/peliculas/<%= @pelicula.id %>" data-width="770" data-num-posts="15" data-colorscheme="dark"></div>
	  
	</div>
</div>